# Generated by Django 4.2.4 on 2023-08-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('composition', models.TextField()),
                ('prodapp', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Milk'), ('Y', 'Yougurt'), ('O', 'Milk Products')], max_length=2)),
                ('images', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='MilkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='milkproduct')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
