# Generated by Django 4.2.4 on 2023-08-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart_image_cart_milk_product_id_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='milk_product_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
