# Generated by Django 4.2.4 on 2023-09-03 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_address_remove_account_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_cart_mproduct_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paypal_order_id', models.CharField(default=None, max_length=100)),
                ('paypal_payment_status', models.CharField(default=None, max_length=100)),
                ('paypal_payment_id', models.CharField(default=None, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Đã xác nhận', 'Đã xác nhận'), ('Đóng gói', 'Đóng gói'), ('Mang đi', 'Mang đi'), ('Đã giao', 'Đã giao'), ('Huỷ đơn', 'Huỷ đơn'), ('Chờ xác nhận', 'Chờ xác nhận')], default='Chờ xác nhận', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('mproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.milkproduct')),
                ('payment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
